// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RPCService.proto

package com.game.pb.service;

public final class RPCServiceProto {
  private RPCServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020RPCService.proto\022\nrpcservice\032\017TestHell" +
      "o.proto2B\n\nRPCService\0224\n\010SayHello\022\023.hell" +
      "o.HelloRequest\032\021.hello.HelloReply\"\000B(\n\023c" +
      "om.game.pb.serviceB\017RPCServiceProtoP\001b\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.game.pb.service.TestHello.getDescriptor(),
        }, assigner);
    com.game.pb.service.TestHello.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
