// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ErrorCode.proto

package com.game.pb.server.message.error;

public final class ErrorCodeOuterClass {
  private ErrorCodeOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code ErrorCode}
   */
  public enum ErrorCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOW = 0;</code>
     */
    UNKNOW(0),
    /**
     * <code>UID_NULL = 1;</code>
     */
    UID_NULL(1),
    /**
     * <code>GAME_PLAYER_NULL = 2;</code>
     */
    GAME_PLAYER_NULL(2),
    /**
     * <code>PARAM_ERROR = 3;</code>
     */
    PARAM_ERROR(3),
    /**
     * <code>RESOURCE_ERROR = 4;</code>
     */
    RESOURCE_ERROR(4),
    /**
     * <code>SESSION_ERROR = 5;</code>
     */
    SESSION_ERROR(5),
    /**
     * <code>NET_ERROR = 6;</code>
     */
    NET_ERROR(6),
    /**
     * <code>CMD_NULL = 7;</code>
     */
    CMD_NULL(7),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNKNOW = 0;</code>
     */
    public static final int UNKNOW_VALUE = 0;
    /**
     * <code>UID_NULL = 1;</code>
     */
    public static final int UID_NULL_VALUE = 1;
    /**
     * <code>GAME_PLAYER_NULL = 2;</code>
     */
    public static final int GAME_PLAYER_NULL_VALUE = 2;
    /**
     * <code>PARAM_ERROR = 3;</code>
     */
    public static final int PARAM_ERROR_VALUE = 3;
    /**
     * <code>RESOURCE_ERROR = 4;</code>
     */
    public static final int RESOURCE_ERROR_VALUE = 4;
    /**
     * <code>SESSION_ERROR = 5;</code>
     */
    public static final int SESSION_ERROR_VALUE = 5;
    /**
     * <code>NET_ERROR = 6;</code>
     */
    public static final int NET_ERROR_VALUE = 6;
    /**
     * <code>CMD_NULL = 7;</code>
     */
    public static final int CMD_NULL_VALUE = 7;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ErrorCode valueOf(int value) {
      return forNumber(value);
    }

    public static ErrorCode forNumber(int value) {
      switch (value) {
        case 0: return UNKNOW;
        case 1: return UID_NULL;
        case 2: return GAME_PLAYER_NULL;
        case 3: return PARAM_ERROR;
        case 4: return RESOURCE_ERROR;
        case 5: return SESSION_ERROR;
        case 6: return NET_ERROR;
        case 7: return CMD_NULL;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ErrorCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ErrorCode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ErrorCode>() {
            public ErrorCode findValueByNumber(int number) {
              return ErrorCode.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.game.pb.server.message.error.ErrorCodeOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final ErrorCode[] VALUES = values();

    public static ErrorCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ErrorCode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ErrorCode)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017ErrorCode.proto*\220\001\n\tErrorCode\022\n\n\006UNKNO" +
      "W\020\000\022\014\n\010UID_NULL\020\001\022\024\n\020GAME_PLAYER_NULL\020\002\022" +
      "\017\n\013PARAM_ERROR\020\003\022\022\n\016RESOURCE_ERROR\020\004\022\021\n\r" +
      "SESSION_ERROR\020\005\022\r\n\tNET_ERROR\020\006\022\014\n\010CMD_NU" +
      "LL\020\007B\"\n com.game.pb.server.message.error" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
