// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RPCTestHello.proto

package com.game.pb.server.rpc.hello;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hello.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
