// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RPCTestHello.proto

package com.game.pb.server.rpc.hello;

public interface HelloReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hello.HelloReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
